version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.2.3
functions:
  email:
    lang: golang-middleware
    handler: ./micro1
    image: qolzam/micro1:0.1
    annotations:
      edge.gateway: "http://inlets.default/"
      edge.user: "hWICHHkLKgve1vwcQa9I3GMsmXgo"
      edge.password: "XVA9vEgKLShTecxfOeixbkXTarsjFcTNIu8W2g=="
